"""change_pressure_type

Revision ID: e6c792fd3f7f
Revises: a4170082a227
Create Date: 2023-11-24 10:59:27.483983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6c792fd3f7f'
down_revision = 'a4170082a227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festo_current_detail', schema=None) as batch_op:
        batch_op.alter_column('pressure',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('festo_history', schema=None) as batch_op:
        batch_op.alter_column('pressure',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festo_history', schema=None) as batch_op:
        batch_op.alter_column('pressure',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('festo_current_detail', schema=None) as batch_op:
        batch_op.alter_column('pressure',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
